
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module top(
	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire					[3:0]		RAM1out;
	wire					[3:0] 	RAM0out;
	wire								enable_one;
	wire								enable_zero;


//=======================================================
//  Structural coding
//=======================================================

	assign enable_one = SW[9] & SW[8];
	assign enable_zero = SW[9] & ~SW[8];

	singlePortRam RAM1(SW[7:4], SW[3:0], enable_one, KEY[0], RAM1out);
	singlePortRam RAM0(SW[7:4], SW[3:0], enable_zero, KEY[0], RAM0out);

	assign HEX5[7:0] = 8'b11111111;
	assign HEX4[7:0] = 8'b11111111;
	hexDisplay	hex3(SW[7:4], HEX3[7:0]);
	hexDisplay	hex2(SW[3:0], HEX2[7:0]);
	hexDisplay	hex1(RAM1out, HEX1[7:0]);
	hexDisplay	hex0(RAM0out, HEX0[7:0]);
	
endmodule
